package models

import "time"

// MissingItem represents a recommended vaccine dose that is missing
type MissingItem struct {
	VaccineName          string     `json:"vaccine_name"`
	Description          string     `json:"description"`
	EarliestNextDoseDate *time.Time `json:"earliest_next_dose_date,omitempty"`
	StatusTags           []string   `json:"status_tags"`
}

// AnalysisResult contains all the recommendations generated by the engine
type AnalysisResult struct {
	MissingItems []MissingItem `json:"missing_items"`
}
